[project]
name = "mcp-client-ollama"
version = "0.1.0"
description = "MCP Client for Ollama"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.6.0",
    "ollama>=0.4.8",
    "rich>=14.0.0",
]
